### ISSUE TITLE
2个

### ISSUE THREAD

**Issue by EstelleC1104** [carolcoral/no-free_vpn#12]
1、express被发现有问题
2、还有几个不知可有参与对比：SGreen（ https://github.com/newbreedlimited/SGreenVPN-iOS ）， brook（ https://github.com/txthinking/brook ） ， Psiphon（ https://github.com/Psiphon-Inc/psiphon-ios-vpn#psiphon-ios-vpn ）

**Comment by carolcoral** [comment]
这几个没用过，不太清楚，不过那个sgreen是原来的greenvpn吗
