### ISSUE TITLE
shadowsocks挂了

### ISSUE THREAD

**Issue by lichangao1826** [carolcoral/no-free_vpn#9]

**Comment by carolcoral** [comment]
@lichangao1826 是的，昨天挂掉的，因为最近国家处于活动敏感时期，预计将会长达3个月无法正常使用vpn，目前已发现ss和搬瓦工均被封掉了国内的代理ip和端口

**Comment by akirasen** [comment]
其它梯子 不谢 https://fileem.com/how-can-the-shadowsocket-ladder-not-be-used-2-5-knives-a-month-try-to-build-a-ladder-with-v2ray-ten-minutes-to-build-the-most-complete-ladder-tutorial-in-history

**Comment by carolcoral** [comment]
@akirasen 谢谢，不过目前ss可以使用了，但是当前可用为日本节点，经过测试香港、澳大利亚、美国节点仍不可用

**Comment by carolcoral** [comment]
@akirasen 谢谢你的使用教程，vlutr已经添加到home中了。
